version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: 1
    ports:
      - '5000:5000'